TARGET = iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = SwiftTestApp

include /home/runner/theos/makefiles/common.mk

APPLICATION_NAME = SwiftTestApp

SwiftTestApp_FILES = ContentView.swift SwiftTestAppApp.swift

include /home/runner/theos/application.mk
