TARGET = iphone:clang:latest:15.0
INSTALL_TARGET_PROCESSES = SwiftTestApp

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = SwiftTestApp

SwiftTestApp_FILES = ContentView.swift SwiftTestAppApp.swift

include $(THEOS_MAKE_PATH)/application.mk
